notification:
  cooldownSeconds: 1
  opEnabled: true
  fileLogging: true
  consoleLogging: false
  permissionsEnabled: true
  permissions:
    - staff.admin
    
## allows players to access containers through these blocks
canClickThrough:
  - 1
  - REDSTONE_DUST
  
## doesn't check when accessing these containers
containersToIgnore:
  - DISPENSER