notification:
  cooldownSeconds: 1
  opEnabled: true
  consoleEnabled: true
  permissionsEnabled: true
  permissions:
    - staff.admin
  broadcastAutobans: true
  broadcastAutobansAdmin: true
  autobanGloatMessages:
    - "What a loser..."
    - "Get wrecked mate"
    - "Go hack on another server"
    - "*inb4 an appeal is made*"
    - "Alright, admins can calm down now"
    - "Who needs admins when you've got JAC?"
    - "*Cracks knuckles*"
    - "And the crowd goes wild"
    - "This autoban was brought to you by JAC. We also make delicious ice cream."
    
banning:
  kickInstead: false
  runCommands: true
  lengthDays:
    LIGHT: 4
    MEDIUM: 7
    HEAVY: 30
  bansTilPerm:
    LIGHT: 3      
    MEDIUM: 2
    HEAVY: 2
  unbanTier:
    LIGHT: 1
    MEDIUM: 1
    HEAVY: 1
    PERMANENT: 2
    UNIQUE: 3

logging: 
  file: true
  singleFile: true
  console: false

AutoArmor:
  enabled: true
  level: MEDIUM
  autoban: false
  autoequipTicks: 8
  addPingToTicks: true

WallHack:
  enabled: true
  level: MEDIUM
  autoban: false
  canClickThrough:
    - REDSTONE_DUST
  containersToIgnore:
    - DISPENSER
    
CivBreak:
  enabled: true
  level: HEAVY
  autoban: true