main: jdz.jac.JAC
name: JAC
version: 1.0
author: Jonodonozym
description: Jono's Anticheat
softdepend: [JBU]

commands:
  jac:
    permission: jac.admin

permissions:
  jac.admin:
    default: op
